### ISSUE TITLE
As a specialist I can open a new ticket (help request)

### ISSUE THREAD

**Issue by barakd** [dorldor/help-on-the-way#20]
I will have a screen with a form where I can put all the needed information for creating a new ticket.

Sample Mock(not finalized, not the real fields, just to get the general intent)
![image](https://user-images.githubusercontent.com/7824284/34870524-fec9e3bc-f792-11e7-9125-870d5a5fa095.png)

**Comment by OhadRon** [comment]
When we flesh out the spec, several things we need to take into consideration:
1. We should consider adding the option to search for existing elders in order to prevent dupes and reduce the time it take to create a ticket if the elder is already 'onboarded'. Same goes for referrer.
2. Address picker - should probably be some combination of map / address search component + a description field ('The red door next to the lion statue'..)
3. The tag system we discussed - some of the things in the mock could be expressed as tags (e.g. Car required, technical expertise, escort, long duration etc)

**Comment by barakd** [comment]
Totaly agree, will make sure these points will be taken into consideration during the design\ux phase.

**Comment by IdoMor** [comment]
Consider making the outer layout as a separate task to remove dependencies. 
Then the inner views (open ticket, view ticket, and status) should be navigated using some inner route

**Comment by OhadRon** [comment]
@IdoMor Yes, I've already built the basic infrastructure for tabbed navigation with vue-router.
Specifically for the open ticket/view-ticket/status parts - depending on design decisions, it's more of a ['step'](http://element.eleme.io/#/en-US/component/steps) UI and not quite a tabbed navigation.

**Comment by IdoMor** [comment]
@OhadRon How should I continue with this?
How does this comes along with 'Implement new ticket flow'?

**Comment by OhadRon** [comment]
I'm on this - I'm in talks with Ben about how this should be implemented. The specs are not complete yet - check out the PDF I sent in the WhatsApp group yesterday.

**Comment by barakd** [comment]
Main ticket creation flows are done.
